# Generated by Django 3.1.2 on 2020-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201022_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_stripe_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
