# Generated by Django 3.1.2 on 2020-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_default_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_subscription',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
