# Generated by Django 3.1.2 on 2020-11-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_default_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_app',
            field=models.CharField(choices=[('select', 'Selecteaza aplicatia *'), ('smart_iptv', 'Smart IPTV'), ('set_iptv', 'Set IPTV'), ('net_iptv', 'Net IPTV'), ('iptv_extreme', 'IPTV Extreme'), ('mag_device', 'Dispozitiv MAG'), ('stb_device', 'Dispozitiv STB'), ('another_device', 'Alt dispozitiv')], default='select', max_length=40),
        ),
    ]
