# Generated by Django 3.1.2 on 2020-10-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201023_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
