# Generated by Django 3.1.2 on 2020-10-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='canceled',
            new_name='status',
        ),
    ]
