# Generated by Django 3.1.2 on 2020-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20201024_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='STAND-BY', max_length=40, null=True),
        ),
    ]
