# Generated by Django 3.1.2 on 2020-11-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_activesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_date_created',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_date_end',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_date_start',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
