# Generated by Django 3.1.2 on 2020-11-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20201105_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscription',
            name='sub_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
