# Generated by Django 3.1.2 on 2020-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_1',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_10',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_3',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_4',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_5',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_6',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_7',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_8',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_9',
            field=models.TextField(max_length=254),
        ),
    ]
