# Generated by Django 3.1.2 on 2020-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201016_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_1',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_10',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_3',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_4',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_5',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_6',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_7',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_8',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_9',
            field=models.CharField(max_length=254),
        ),
    ]
